### ISSUE TITLE
Audio device could not be found

### ISSUE THREAD

**Issue by mike-lt** [littlecraft/phony#13]
Hi

I'm using this library on Ubuntu 18.04 with python 3.6. I edited some files to make it work (like print and exception function which has python2.7 syntax).
I tried to execute the example code in Usage but I'm having the following error:
`An audio device with a speaker and a microphone mixer is required, but could not be found. card_index=-1`
I also tried to set the card index to 0 or to 1 but I'm still having the error.

**Comment by mutac** [comment]
Hi,

Great to hear that you've gotten things to work with python 3.6.  I'd gladly accept a PR with your changes.

Regarding the audio device, in reality phony isn't really in charge of which audio device pulseaudio & ophono choose to use as the audio gateway (which is sort of a "gotcha" in a way).  At the time of testing, I believe only devices that had both an output and input would be chosen as an audio gateway.  The reason that `phony.headset.HandsFree` takes an instance of a `phony.audio.Alsa` is so that it can (independently of bluez/pulseaudio/ofono) control the audio input and output volumes.  There isn't any technical reason that, at this layer, there needs to be a single audio device for input and output, but I am unsure if the bluez/pulseaudio/ofono layers would correctly recognize this and assemble an audio gateway.

The [README ](https://github.com/littlecraft/phony#audio) makes mention of this, and suggests an inexpensive USB audio device that would work on a Raspberry Pi.  I have not tested phony on later generations of Raspberry Pi, so I'm not exactly sure if the audio hardware is now compatible.
