### ISSUE TITLE
How to get caller number

### ISSUE THREAD

**Issue by emadomedher** [littlecraft/phony#14]
I read everything and looked everywhere and the knowledge is still out of my reach. Sorry to here like this... but how can I get the caller number from the "call" object at incoming call? Thanks for the help!. Great package here 👍

**Comment by mutac** [comment]
Hi,

I don't believe that there's currently a public way to access properties of a call from within an event handler (it's just a path string that refers to a call).  The callback signatures are also unfortunately limited in that they don't provide a "sender" object either.

There's probably a couple of ways to improve things:

1)  Without breaking API compatibility, it might work to modify the `OfonoHfpAg` and the `HandsFreeHeadset` classes so that they provide a way to retrieve call properties given a path.

```python
class ExampleWithLookupByPath:
  _hs = None

  def incoming_call(self, path:string):
    # An example of a new public API that would return call properties, requiring
    # clients to maintain their own reference to the HandsFreeHeadset instance
    print('Incoming: %s' % self._hs.get_call_properties(path)['incoming_line_identification'])
    self._hs.answer_call(path)

  def run(self):
    bus = phony.base.ipc.BusProvider()
    audio_card_index = -1

    with phony.bluetooth.adapters.Bluez5(bus) as adapter, \
         phony.bluetooth.profiles.handsfree.Ofono(bus) as hfp, \
         phony.audio.alsa.Alsa(card_index=audio_card_index) as audio, \
         phony.headset.HandsFreeHeadset(bus, adapter, hfp, audio) as hs:

      self._hs = hs
      self._hs.on_incoming_call(self.incoming_call)
      # ...
```

2.  Make a breaking API change so that the callbacks are provided an object that represents a call (not just a path string), and have that object provide more useful information about the call.  And if we're breaking the API, we might as well add in a "sender" argument too to the callbacks into which the instance of the HandsFreeHeadset class could be passed as well.  Going this route, all of the other methods that refer to a call by path string should probably also be updated so that they can be used to refer to call by an object as well.

```python
class ExampleWithCallObject:
  def incoming_call(self, headset:HandsFreeHeadset, call_obj:Call):
    # An example of a breaking API change where a callback receives an object
    # rather than a path string.
    print('Incoming: %s' % call_obj.incoming_line_identification)
    headset.answer_call(call_obj)

  def run(self):
    bus = phony.base.ipc.BusProvider()
    audio_card_index = -1

    with phony.bluetooth.adapters.Bluez5(bus) as adapter, \
         phony.bluetooth.profiles.handsfree.Ofono(bus) as hfp, \
         phony.audio.alsa.Alsa(card_index=audio_card_index) as audio, \
         phony.headset.HandsFreeHeadset(bus, adapter, hfp, audio) as hs:

      hs.on_incoming_call(self.incoming_call)
      # ...

```

3. Somehow maintain API compatibility, and still allow callbacks to receive a "call object" _or_  a path string.


OR if you don't mind using non-public methods & properties, you could probably access the `_calls` collection of  `OfonoHfpAg` by digging into the the `_hfp_audio_gateway` property of `HandsFreeHeadset`.  Something along the lines of:

```python
ofono_call_obj = hs._hfp_audio_gateway._calls[path]
properties = ofono_call_obj.GetProperties()
print(properties['LineIdentification']
```


As far as getting the actual details of a call, this is how to retrieve them from an Ofono call object:

https://github.com/littlecraft/phony/blob/master/src/phony/bluetooth/profiles/handsfree/ofono.py#L238

The properties are documented here:
https://github.com/rilmodem/ofono/blob/master/doc/voicecall-api.txt

**Comment by emadomedher** [comment]
Asked for a fish, You just taught me how to fish instead.... many thanks!
