### ISSUE TITLE
Error while running the example project on the Raspberry Pi

### ISSUE THREAD

**Issue by maksimus1982** [littlecraft/phony#2]
Hello!
I'm very interesting with your project.
I try to run the example on my Raspberry Pi board (Model B+)
But I catch the error :
**File "/usr/local/lib/python2.7/dist-packages/phony/audio/alsa.py", line 23, in start
    raise Exception('No speaker mixer found. card_index = "%s"' % self._card_index)**

But no any sound problems in my board. And all files in /test/ folder run's without any error.
For example the file **/phony/test/alsa.py** give output message : **Available mixer controls:
  'PCM'**
Can you help me to solve this error ?

**Comment by mutac** [comment]
Hi @maksimus1982,

Sorry for the delay, I didn't notice this until right now.   I suspect that this might be a bit of a bug in alsa.py.  The expected behavior is to throw an exception if an audio device with a speaker mixer and a microphone mixer cannot be found.  I think that the exception text is misleading, but that you are trying to run it on a raspi that does not have a suitable audio device attached to it.  You'll need a usb audio adapter that has both a microphon input and a speaker output.

I am still in the process of fully documenting the project that turns an antique hand-crank telephone into a bluetooth headset, so the description of how the raspi is wired & hooked up to accompany this example code is pretty lacking, as you can see :-(

I'll spend some time soon to get things updated so that it's easier to follow.

**Comment by mutac** [comment]
The error reporting to `phony.audio.alsa` has been modified to make it a bit more clear that an audio device with both a microphone and a speaker mixer is expected to be present,
