### ISSUE TITLE
Raspberry Pi Issues

### ISSUE THREAD

**Issue by sjdean** [littlecraft/phony#7]
Im using a Raspberry Pi 3 running Jessie.

Unfortunately the bundled version of the alsaaudio module does not have the relevent options that the alsa.py script is looking for - cardindex for example is missing.

Never mind, we can install alsaaudio manually and bring up to v0.84 - this should be made clear I think in the requirements if not already.

Secondly, on my Pi, I don't have a combined speaker/mic. In fact, I have no speaker at all.

I don't have full details in front of me at the moment, but the first card index shows PCM, and the second card index shows my USB microphone, which does correctly show as Mic.

I have made some modification, to try and separate the finding of the Microphone and Speaker, but alas, this gives me:

alsaaudio.ALSAAudioError: Mixer Mic,0 has no playback switch capabilities

Maybe phony is the wrong application? I want to turn my Raspberry Pi into a Hands Free device like a car radio that I can use to phone people through my mobile phone.

Simon

**Comment by mutac** [comment]
@sjdean Hey, you definitely can use phony to create an application for the raspberry pi that'll let you make hands-free calls from your mobile.

Thanks for pointing out the compatibility issue with pyalsaaudio.  It sounds like the correct version should be specifically called for in setup.py.

Otherwise, to be able to run such an application on a raspberry pi (or any other platform), you do need to have a single audio device that provides both audio input and output.  I have a link to such an audio device (usb) that I have used successfully on a raspberry pi (See Appendix A in the README).  As far as I am aware, this is a requirement imposed by the underlying bluetooth telephony stack of linux (bluez, ofono, and pulseaudio).

Do you have any audio devices connected to your raspberry pi, or are you talking about the ones that are integrated into the pi?  Just to reiterate, you'll need an external usb audio device that has an output and a mic input to run a phony-based application on a pi.  Phony explicitly checks to make sure that such a device exists because it doesn't seem very useful to provide a telephony service where you can either only hear, or only speak.  What do you get with a `arecord -l`?
